# Generated by Django 5.0.6 on 2024-06-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_product_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_categorie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='base.categorie'),
        ),
    ]
